import { lorem, image } from "faker"

export default {
	items: [
		{
			id: 0,
			position: 0,
			isDragging: false,
			isSlipZone: false,
			title: {
				text: lorem.words(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			subtitle: {
				text: lorem.words(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			paragraph: {
				text: lorem.paragraph(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			image: image.image(),
		},
		{
			id: 1,
			position: 1,
			isSlipZone: false,
			isDragging: false,
			title: {
				text: lorem.words(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			subtitle: {
				text: lorem.words(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			paragraph: {
				text: lorem.paragraph(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			image: image.image(),
		},
		{
			id: 2,
			position: 2,
			isDragging: false,
			isSlipZone: false,
			title: {
				text: lorem.words(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			paragraph: {
				text: lorem.paragraph(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
		},
		{
			id: 3,
			position: 3,
			isSlipZone: false,
			isDragging: false,
			paragraph: {
				text: lorem.paragraph(),
				top: "unset",
				left: "unset",
				isDragging: false,
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			image: image.image(),
		},
	],
	isEditor: true,
	currentItem: {
		id: 0,
		position: 0,
	},
	draggedItem: {
		id: null,
		position: null,
	},
	slipAfterItem: {
		id: null,
		position: null,
	},
}
