export default {
	items: [
		{
			id: 0,
			position: 0,
			isDragging: false,
			isSlipZone: false,
			title: {
				text: "This is the first slide",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			subtitle: {
				text: "First slide",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			paragraph: {
				text: "A super text about the first slide, I mean, really awesome text. I mean it, really.",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			image: "http://wpc.475d.edgecastcdn.net/00475D/facebook_cruise_heros_2/Oceans/In-Search-Northern-Lights_702x468.jpg",
		},
		{
			id: 1,
			position: 1,
			isSlipZone: false,
			isDragging: false,
			title: {
				text: "The yonder beckons",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			subtitle: {
				text: "Shall wait",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			paragraph: {
				text: "I'm leaving now, on a trail of sulphur and salt, yes I'm leaving, to the havens where all things halt",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			image: "http://wpc.475d.edgecastcdn.net/00475D/facebook_cruise_heros_2/Oceans/In-Search-Northern-Lights_702x468.jpg",
		},
		{
			id: 2,
			position: 2,
			isDragging: false,
			isSlipZone: false,
			title: {
				text: "Past the seven and even hours",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			subtitle: {
				text: null,
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			paragraph: {
				text: "Saturnine in my mind the only way I've ever been, saturnine in my mind, high I sail the astral seas",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			image: null,
		},
		{
			id: 3,
			position: 3,
			isSlipZone: false,
			isDragging: false,
			title: {
				text: null,
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			subtitle: {
				text: null,
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			paragraph: {
				text: "Patterns of evil, forever in my mind, beware the sabbath, impure, wicked, witchcraft, disciples of death",
				top: "unset",
				left: "unset",
				x: null,
				y: null,
				offsetX: null,
				offsetY: null,
			},
			image: "http://wpc.475d.edgecastcdn.net/00475D/facebook_cruise_heros_2/Oceans/In-Search-Northern-Lights_702x468.jpg",
		},
	],
	isEditor: true,
	isSliderFullview: false,
	isEditing: false,
	x: 0,
	y: 0,
	offsetX: 0,
	offsetY: 0,
	currentItem: {
		id: 0,
		position: 0,
	},
	draggedItem: {
		id: null,
		position: null,
	},
	slipAfterItem: {
		id: null,
		position: null,
	},
}
